name: annotation-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-doc=0.0.4
  - annotated-types=0.7.0
  - anyio=4.12.0
  - backports.zstd=1.2.0
  - black=25.12.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - dnspython=2.8.0
  - email-validator=2.3.0
  - email_validator=2.3.0
  - exceptiongroup=1.3.1
  - fastapi=0.124.4
  - fastapi-cli=0.0.16
  - fastapi-core=0.124.4
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - libcxx=21.1.7
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.1
  - libuv=1.51.0
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - mdurl=0.1.2
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - openssl=3.6.0
  - packaging=25.0
  - pathspec=0.12.1
  - pip=25.3
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.12.12
  - python-dotenv=1.2.1
  - python-multipart=0.0.20
  - python_abi=3.12
  - pytokens=0.3.0
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - rich=14.2.0
  - rich-toolkit=0.17.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - starlette=0.50.0
  - tk=8.6.13
  - tomli=2.3.0
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.2
  - uvicorn=0.38.0
  - uvicorn-standard=0.38.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - yaml=0.2.5
  - zstd=1.5.7
prefix: /opt/miniconda3/envs/annotation-engine
